"""`SourceRef` — the cross-cutting provenance reference (CR-19). **Identity = `content_hash` (PRIMARY); location = `locator`; region = optional atomic typed `slice`.** `verify()` is hash-based regardless of whether the locator still resolves — the structural fix for dangling row-id provenance (cache-hit rows; ledgers E13/D3).

Docs: https://cj-mills.github.io/cjm-context-graph-primitivesprovenance.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/provenance.ipynb.

# %% auto #0
__all__ = ['SourceRef']

# %% ../nbs/provenance.ipynb #e9105179
from dataclasses import dataclass
from typing import Any, Dict, Optional

from cjm_plugin_system.core.errors import PluginInputError
from cjm_plugin_system.utils.hashing import hash_bytes, verify_hash

from .locators import ResourceLocator, locator_from_dict
from .slices import TypedSlice, slice_from_dict

# %% ../nbs/provenance.ipynb #7cdef44b
@dataclass(frozen=True)
class SourceRef:
    """A provenance reference to (a region of) a resource.

    Replaces the old plugin_name/table_name/row_id/segment_slice shape: the
    locator is a structured sum type (no `external:<path>` string abuse), the
    hash is primary identity, and the slice is typed and atomic.
    """
    locator: ResourceLocator           # WHERE the content lives/lived (may dangle without breaking verifiability)
    content_hash: str                  # PRIMARY identity: "algo:hexdigest" over the CONSUMED (sliced) content
    slice: Optional[TypedSlice] = None  # Consumed region, framed to the locator target; None = whole resource

    def to_uri(self) -> str:  # Canonical string: "<locator-uri>[#<slice-string>]@<content_hash>"
        """Render the complete canonical string form (grep-able by locator, slice, or hash)."""
        base = self.locator.to_uri()
        if self.slice is not None:
            base = f"{base}#{self.slice.to_slice_string()}"
        return f"{base}@{self.content_hash}"

    def __str__(self) -> str:  # Same as `to_uri`
        return self.to_uri()

    def to_dict(self) -> Dict[str, Any]:  # Nested wire dict
        """Serialize to the wire dict form."""
        return {
            "locator": self.locator.to_dict(),
            "content_hash": self.content_hash,
            "slice": self.slice.to_dict() if self.slice is not None else None,
        }

    @classmethod
    def from_dict(
        cls,
        d: Dict[str, Any]  # Wire dict with nested locator/slice dicts
    ) -> "SourceRef":  # Reconstructed reference (unknown locator/slice kinds round-trip)
        """Reconstruct from the wire dict form."""
        if "locator" not in d or "content_hash" not in d:
            raise PluginInputError(
                f"SourceRef dict missing required keys: {sorted(d.keys())!r}",
                fields_invalid=[k for k in ("locator", "content_hash") if k not in d],
            )
        sl = d.get("slice")
        return cls(
            locator=locator_from_dict(d["locator"]),
            content_hash=d["content_hash"],
            slice=slice_from_dict(sl) if sl is not None else None,
        )

    def verify(
        self,
        current_content: bytes  # Current bytes of the CONSUMED (sliced) content
    ) -> bool:  # True if content still matches the stored hash
        """Hash-verify content — works even when the locator no longer resolves."""
        return verify_hash(current_content, self.content_hash)

    @staticmethod
    def compute_hash(
        content: bytes,       # Content to hash
        algo: str = "sha256"  # Hash algorithm name
    ) -> str:  # Hash string in "algo:hexdigest" format
        """Compute a content hash for use in a SourceRef."""
        return hash_bytes(content, algo)
